package com.revaisor.ai_integration_backend.service;

import org.springframework.ai.ollama.OllamaChatModel;

/**
 * Interface for AI service operations
 * Defines the contract for generating responses from AI models
 */

public interface AiService {
    /**
     * Generates a response from the AI model
     * @param message Input message from the user
     * @return A response generated by the AI
     */
    String generateResponse(String message);
    String generateResponse(String message, String modelName);
}
