services:
  backend:
    build:
      context: ./Backend/ai-integration-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - backend-data:/app/data
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/frontend-ai-revaisor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api/ai
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  backend-data:
  ollama-data:

networks:
  app-network:
    driver: bridge
