package com.revaisor.ai_integration_backend.service.impl;

import com.revaisor.ai_integration_backend.service.AiService;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.ollama.OllamaChatModel;
import org.springframework.stereotype.Service;


// Implementation of AiService using Ollama model
@Service
public class ollamaAiService implements AiService {

    private final ChatClient chatClient;

    public ollamaAiService(OllamaChatModel chatModel) {
        this.chatClient = ChatClient.create(chatModel);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String generateResponse(String message) {

        /**
         * Generates a response from the AI model
         * @param message Input message from the user
         * @return A response generated by the AI
         */
        try {
            return chatClient
                    .prompt(message)
                    .call()
                    .content();
        } catch (Exception e) {
            throw new RuntimeException("Error generating response", e);
        }
    }
}
