# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml


# Spring Configuration
spring:
  application:
    name: revaisor-ai-backend


  datasource:
    url: jdbc:h2:file:./data/feedback-db
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
        ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect_storage_engine: true

  h2:
    console:
      enabled: true
      path: /h2-console



  # Deepseek Configuration
  ai:
    ollama:
      init:
        pull-model-strategy: always
        chat:
          additional-models:
            - deepseek-r1:7b
            - qwen2.5:3b
    openai:
      api-key: ${OPENAI_API_KEY}
      organization-id: ${OPENAI_ORG_ID}
      project-id: ${OPENAI_PROJECT_ID}
      chat:
        options:
          model:
            - gpt-3.5-turbo
            - gpt-4o


  # Json Configuration
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false



