package com.revaisor.ai_integration_backend.service.AI.impl;

import com.revaisor.ai_integration_backend.exception.RequestValidator;
import org.springframework.ai.chat.messages.Message;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public abstract class AbstractAiService implements AiService {

    private Map<String, Resource> promptResources;

    @Autowired
    protected RequestValidator requestValidator;

    @Value("classpath:prompts/Math-Assistant.st")
    private Resource mathAssistantPrompt;

    @Value("classpath:prompts/Software-Assistant.st")
    private Resource softwareEngineerPrompt;

    @Value("classpath:prompts/Car-Assistant.st")
    private Resource carAssistantPrompt;

    @Value("classpath:prompts/Sports-Assistant.st")
    private Resource sportsAssistantPrompt;

    @Value("classpath:prompts/Travel-Assistant.st")
    private Resource travelAssistantPrompt;


    /**
     * Returns a map of prompt resources for different assistant types
     * @return Map of prompt resources
     */
    public Map<String, Resource> getPromptResources() {
        if (promptResources == null) {
            promptResources = Map.of(
                    "math", mathAssistantPrompt,
                    "software", softwareEngineerPrompt,
                    "car", carAssistantPrompt,
                    "sports", sportsAssistantPrompt,
                    "travel", travelAssistantPrompt
            );
        }
        return promptResources;
    }

    /**
     * Generates a response from the AI model based on the input message and assistant type
     * @param message Input message from the user
     * @param assistantType Type of assistant (e.g., math, software, car, sports, travel)
     * @return A String and resource containing the generated response
     */

    @Override
    public String generateResponse(String message, String assistantType) {

        String validationResult = requestValidator.verification(message);
        String sanitizedMessage = sanitizeMessage(message);

        if (!validationResult.equals("valid request")) {
            return validationResult;
        }

        Resource promptResource = getPromptResources().getOrDefault(
                assistantType.toLowerCase(),
                mathAssistantPrompt
        );

        return generateAssistant(sanitizedMessage, promptResource);
    }

    /**
     * Generates a response from the AI model using the provided message and prompt resource
     * @param message Input message from the user
     * @param promptResource Resource containing the prompt for the assistant
     * @return A response generated by the AI
     */
    private String generateAssistant(String message, Resource promptResource) {
        try {
            String promptContent = new String(promptResource.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
            String sanitizedMessage = requestValidator.sanitize(message);

            List<Message> messages = new ArrayList<>();
            messages.add(new SystemMessage(promptContent));
            messages.add(new UserMessage(sanitizedMessage));

            return callModelWithPrompt(messages);

        } catch (Exception e) {
            throw new RuntimeException("Error generating response" + getServiceName(), e);
        }
    }

    /**
     * Sanitizes the input message to ensure it is safe for processing
     * @param message Input message from the user
     * @return A sanitized version of the input message
     */

    private String sanitizeMessage(String message) {
        String validationResult = requestValidator.verification(message);
        if (!validationResult.equals("valid request")) {
            return validationResult;
        }
        return requestValidator.sanitize(message);
    }

    protected abstract String callModelWithPrompt(List<Message> messages);

    protected abstract String getModelName();

    protected abstract double getTemperature();

    protected abstract String getServiceName();

}
